# Generated by Django 2.2.26 on 2022-02-03 17:52

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ifxbilling.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ifxuser', '0006_useraffiliation_detail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, help_text='Account code (e.g. expense code or PO number)', max_length=50)),
                ('account_type', models.CharField(choices=[('Expense Code', 'Expense Code'), ('PO', 'PO')], default='Expense Code', help_text='Expense Code or PO', max_length=20)),
                ('name', models.CharField(blank=True, help_text='Short, human readable name for this code', max_length=100, null=True)),
                ('root', models.CharField(blank=True, default=None, help_text='If it is an expense code, the last 5 digits', max_length=5, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', message='Root must be 5 digits.')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('valid_from', models.DateField(blank=True, default=ifxbilling.models.thisDate)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('slug', models.CharField(help_text='EC or PO + institution', max_length=100, unique=True)),
                ('funding_category', models.CharField(blank=True, max_length=100, null=True)),
                ('organization', models.ForeignKey(help_text='Organization responsible for the account.', on_delete=django.db.models.deletion.PROTECT, to='ifxuser.Organization')),
            ],
            options={
                'db_table': 'account',
                'unique_together': {('code', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.IntegerField(default=0, help_text='Sum of charge records in pennies')),
                ('percent', models.IntegerField(default=100, help_text='Percent of total product usage cost that this charge represents, defaults to 100%')),
                ('description', models.CharField(blank=True, default='', help_text='Description of the billing record.', max_length=1000, null=True)),
                ('year', models.IntegerField(default=ifxbilling.models.thisYear, help_text='Calendar year to which the billing applies')),
                ('month', models.IntegerField(default=ifxbilling.models.thisMonth, help_text='Month in which the billing applies')),
                ('current_state', models.CharField(blank=True, help_text='Name of the most recent BillingRecordState', max_length=100, null=True)),
                ('rate', models.CharField(blank=True, help_text='Text description of the rate used to calculate the charge', max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.Account')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billingrecord_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'db_table': 'billing_record',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the facility (e.g. Helium Recovery Service)', max_length=200, unique=True)),
                ('application_username', models.CharField(help_text='Username that permits logging in to the facility application (e.g. nice)', max_length=50)),
                ('credit_code', models.CharField(help_text='Credit code to receive funds from billing for product usages.', max_length=50)),
                ('invoice_prefix', models.CharField(help_text='Prefix used in the invoice names for the facility.', max_length=50)),
                ('object_code', models.CharField(default='8250', help_text='Object code for this facility', max_length=4)),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'db_table': 'facility',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(default=None, help_text='Product number of the form IFXP0000000000', max_length=14, unique=True)),
                ('product_name', models.CharField(default=None, help_text='Name of the product', max_length=50, unique=True)),
                ('product_description', models.CharField(default=None, help_text='Product description', max_length=200)),
                ('billing_calculator', models.CharField(blank=True, default='ifxbilling.calculator.BasicBillingCalculator', help_text='Class to use for calculating charges for this product', max_length=100)),
                ('reporting_group', models.CharField(blank=True, max_length=100, null=True)),
                ('billable', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.Facility')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='Calendar year in which the usage occurs')),
                ('month', models.IntegerField(help_text='Month in which the usage occurs')),
                ('quantity', models.BigIntegerField(default=1, help_text='Quantity of product')),
                ('units', models.CharField(default='ea', help_text='Units of quantity', max_length=100)),
                ('description', models.CharField(blank=True, help_text='Description of usage', max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('logged_by', models.ForeignKey(help_text='User that logged the usage (may be different than user)', on_delete=django.db.models.deletion.PROTECT, related_name='product_usage_logger', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(help_text='Organization responsible for the account.', on_delete=django.db.models.deletion.PROTECT, to='ifxuser.Organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ifxbilling.Product')),
                ('product_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_usage',
            },
        ),
        migrations.CreateModel(
            name='AccountUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ifxuser.IfxUser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserProductAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(default=100, help_text='Percent of charge that should be applied to this account for the user product')),
                ('is_valid', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.Account')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_product_account',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.IntegerField(default=0, help_text='Positive or negative charge in pennies')),
                ('description', models.CharField(default=None, help_text='Reason for this charge.', max_length=500)),
                ('rate', models.CharField(blank=True, help_text='Text description of the rate used to calculate the charge', max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('billing_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.BillingRecord')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text='Name for this rate', max_length=50)),
                ('price', models.IntegerField(default=0, help_text='Price in pennies')),
                ('units', models.CharField(default=None, help_text='Unit for price (e.g. ea)', max_length=100)),
                ('max_qty', models.IntegerField(blank=True, help_text='Price applys to this number or units or less', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this rate currently active?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.Product')),
            ],
            options={
                'db_table': 'rate',
            },
        ),
        migrations.CreateModel(
            name='ProductUsageProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.CharField(blank=True, help_text='Error message from processing into billing record.', max_length=2000, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.ProductUsage')),
            ],
            options={
                'db_table': 'product_usage_processing',
            },
        ),
        migrations.CreateModel(
            name='BillingRecordState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text='Name of the state', max_length=100)),
                ('comment', models.CharField(blank=True, help_text='Any message associated with the state', max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('approvers', models.ManyToManyField(blank=True, related_name='billing_record_state_approvers', to=settings.AUTH_USER_MODEL)),
                ('billing_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.BillingRecord')),
                ('user', models.ForeignKey(default=None, help_text='User that inserted the state', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_record_state',
                'ordering': ('-created',),
            },
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='product_usage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ifxbilling.ProductUsage'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billingrecord_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_account',
                'unique_together': {('account', 'user')},
            },
        ),
    ]
