# Generated by Django 2.2.14 on 2020-07-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullcode', models.CharField(default=None, help_text='expense code, dash seperated', max_length=50)),
                ('name', models.CharField(blank=True, help_text='short human readable name for this code', max_length=100, null=True)),
                ('root', models.IntegerField(blank=True, default=None, help_text='the root 4 digits of the expense code', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField(auto_now=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'expense_code',
            },
        ),
    ]
