# Generated by Django 2.2.18 on 2021-02-18 20:22

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ifxuser', '0008_ifxuser_primary_affiliation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=None, help_text='Account code (e.g. expense code or PO number)', max_length=50)),
                ('account_type', models.CharField(choices=[('Expense Code', 'Expense Code'), ('PO', 'PO')], default='Expense Code', help_text='Expense Code or PO', max_length=20)),
                ('name', models.CharField(blank=True, help_text='Short, human readable name for this code', max_length=100, null=True)),
                ('root', models.IntegerField(blank=True, default=None, help_text='If it is an expense code, the last 4 digits', null=True, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', message='Root must be 5 digits.')])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('valid_from', models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 18, 20, 22, 17, 367812, tzinfo=utc))),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('slug', models.CharField(help_text='EC or PO + institution', max_length=100, unique=True)),
                ('organization', models.ForeignKey(help_text='Organization responsible for the account.', on_delete=django.db.models.deletion.PROTECT, to='ifxuser.Organization')),
            ],
            options={
                'db_table': 'account',
                'unique_together': {('code', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.IntegerField(default=0, help_text='Sum of charge records in pennies')),
                ('description', models.CharField(blank=True, help_text='Description of the billing record.', max_length=200, null=True)),
                ('year', models.IntegerField(default=2021, help_text='Calendar year to which the billing applies')),
                ('month', models.IntegerField(default=2, help_text='Month in which the billing applies')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ifxbilling.Account')),
            ],
            options={
                'db_table': 'billing_record',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_number', models.CharField(default=None, help_text='Product number of the form IFXP0000000000', max_length=14, unique=True)),
                ('product_name', models.CharField(default=None, help_text='Name of the product', max_length=50, unique=True)),
                ('product_description', models.CharField(default=None, help_text='Product description', max_length=200)),
                ('billing_calculator', models.CharField(default='ifxbilling.calculator.BasicBillingCalculator', help_text='Class to use for calculating charges for this product', max_length=100)),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge', models.IntegerField(default=0, help_text='Positive or negative charge in pennies')),
                ('description', models.CharField(default=None, help_text='Reason for this charge.', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_create', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('billing_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.BillingRecord')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'db_table': 'transaction',
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text='Name for this rate', max_length=50)),
                ('price', models.IntegerField(default=0, help_text='Price in pennies')),
                ('units', models.CharField(default=None, help_text='Unit for price (e.g. ea)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Is this rate currently active?')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.Product')),
            ],
            options={
                'db_table': 'rate',
            },
        ),
        migrations.CreateModel(
            name='ProductUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=2021, help_text='Calendar year in which the usage occurs')),
                ('month', models.IntegerField(default=2, help_text='Month in which the usage occurs')),
                ('quantity', models.IntegerField(default=1, help_text='Quantity of product')),
                ('units', models.CharField(default='ea', help_text='Units of quantity', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ifxbilling.Product')),
                ('product_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_usage',
            },
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='product_usage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ifxbilling.ProductUsage'),
        ),
    ]
