# Generated by Django 2.2.18 on 2021-02-16 18:53

from django.db import migrations
from ifxbilling.init import migrate


class Migration(migrations.Migration):
    '''
    Migration
    '''

    dependencies = [
        ('ifxbilling', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(migrate, migrate)
    ]
