# Generated by Django 2.2.14 on 2020-07-08 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecode',
            name='fullcode',
            field=models.CharField(default=None, help_text='expense code, dash seperated', max_length=50, validators=[django.core.validators.RegexValidator('^[0-9]{3}\\-[0-9]{5}\\-[0-9]{4}\\-[0-9]{6}\\-[0-9]{6}\\-[0-9]{4}\\-[0-9]{5}$', message='Expense code must be dash separated.')]),
        ),
        migrations.AlterField(
            model_name='expensecode',
            name='valid_from',
            field=models.DateTimeField(),
        ),
    ]
