# Generated by Django 2.2.21 on 2021-05-06 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ifxbilling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProductAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(default=100, help_text='Percent of charge that should be applied to this account for the user product')),
                ('is_valid', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.Account')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_product_account',
            },
        ),
    ]
