# Generated by Django 2.2.28 on 2022-07-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='billing_record_template',
            field=models.CharField(blank=True, default='ifxbilling.templates.billing_record_summary_base.html', help_text='template for billing record summary which gets emailed to lab admins', max_length=100),
        ),
    ]
