# Generated by Django 2.2.18 on 2021-04-07 15:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 7, 15, 23, 41, 955189, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='month',
            field=models.IntegerField(default=4, help_text='Month in which the billing applies'),
        ),
        migrations.AlterField(
            model_name='productusage',
            name='month',
            field=models.IntegerField(default=4, help_text='Month in which the usage occurs'),
        ),
    ]
