# Generated by Django 2.2.18 on 2021-02-16 20:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0002_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Expense Code', 'Expense Code'), ('PO', 'PO')], default='Expense Code', help_text='Expense Code or PO', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 16, 20, 49, 38, 513987, tzinfo=utc)),
        ),
    ]
