# Generated by Django 2.2.22 on 2021-05-10 16:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0002_userproductaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='valid_from',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
