# Generated by Django 2.2.18 on 2021-03-05 00:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0002_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingrecord',
            name='account',
        ),
        migrations.AlterField(
            model_name='account',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 5, 0, 11, 2, 169711, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='month',
            field=models.IntegerField(default=3, help_text='Month in which the billing applies'),
        ),
        migrations.AlterField(
            model_name='productusage',
            name='month',
            field=models.IntegerField(default=3, help_text='Month in which the usage occurs'),
        ),
        migrations.CreateModel(
            name='BillingRecordAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.IntegerField(default=100)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.Account')),
                ('billing_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.BillingRecord')),
            ],
            options={
                'db_table': 'billing_record_account',
            },
        ),
    ]
