# Generated by Django 2.2.28 on 2022-08-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0002_facility_billing_record_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='create_billing_records_class',
            field=models.CharField(blank=True, default='ifxbilling.billing_record_generator.BillingRecordGenerator', help_text='The name of the class that selects product usages and creates billing records using the calculator class', max_length=100),
        ),
    ]
