# Generated by Django 2.2.28 on 2022-08-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0002_facility_billing_record_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='decimal_charge',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Decimal version of the charge in dollars and cents.  Intended to replace "charge" field.', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='productusage',
            name='decimal_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Decimal quantity of the Product.  Intended to replace the quantity field.', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='decimal_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Price in dollars and cents', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='decimal_charge',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Decimal version of charge.  Intended to replace "charge" field.', max_digits=19, null=True),
        ),
    ]
