# Generated by Django 2.2.18 on 2021-04-15 15:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0002_auto_20210407_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_valid',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 15, 15, 4, 36, 55638, tzinfo=utc)),
        ),
    ]
