# Generated by Django 2.2.14 on 2020-07-09 15:04

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0002_auto_20200708_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensecode',
            name='root',
            field=models.IntegerField(blank=True, default=None, help_text='the root 4 digits of the expense code', null=True, validators=[django.core.validators.RegexValidator('^[0-9]{4}$', message='Root must be 4 digits.')]),
        ),
        migrations.AlterField(
            model_name='expensecode',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 9, 15, 4, 1, 587784)),
        ),
    ]
