# Generated by Django 2.2.18 on 2021-02-18 18:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0002_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='slug',
            field=models.CharField(default='test', help_text='EC or PO + institution', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 18, 18, 15, 58, 589240, tzinfo=utc)),
        ),
    ]
