# Generated by Django 2.2.18 on 2021-02-18 19:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0003_auto_20210218_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=models.CharField(help_text='EC or PO + institution', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 18, 19, 52, 5, 607248, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default=None, help_text='Name of the product', max_length=50, unique=True),
        ),
    ]
