# Generated by Django 2.2.18 on 2021-02-16 21:16

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0003_auto_20210216_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='root',
            field=models.IntegerField(blank=True, default=None, help_text='If it is an expense code, the last 4 digits', null=True, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', message='Root must be 5 digits.')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 16, 21, 16, 35, 43397, tzinfo=utc)),
        ),
    ]
