# Generated by Django 2.2.18 on 2021-03-05 00:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ifxbilling', '0003_auto_20210305_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 5, 0, 19, 41, 991962, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.Account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_account',
            },
        ),
    ]
