# Generated by Django 2.2.23 on 2021-06-06 02:45

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ifxuser', '0008_ifxuser_primary_affiliation'),
        ('ifxbilling', '0003_auto_20210510_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ifxuser.ifxuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BillingRecordState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text='Name of the state', max_length=100)),
                ('comment', models.CharField(blank=True, help_text='Any message associated with the state', max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('approvers', models.ManyToManyField(blank=True, related_name='billing_record_state_approvers', to=settings.AUTH_USER_MODEL)),
                ('billing_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.BillingRecord')),
                ('user', models.ForeignKey(default=None, help_text='User that inserted the state', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_record_state',
                'ordering': ('-created',),
            },
        ),
    ]
