# Generated by Django 2.2.28 on 2022-08-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0003_auto_20220805_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='billing_record_calculator',
            field=models.CharField(blank=True, default='ifxbilling.calculator.NewBillingCalculator', help_text='The name of the class that selects product usages and creates billing records using the calculator class', max_length=100),
        ),
    ]
