# Generated by Django 2.2.28 on 2022-08-09 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0003_facility_create_billing_records_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facility',
            old_name='create_billing_records_class',
            new_name='billing_record_generator',
        ),
    ]
