# Generated by Django 2.2.18 on 2021-02-16 23:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0004_auto_20210216_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 16, 23, 9, 37, 536953, tzinfo=utc)),
        ),
    ]
