# Generated by Django 2.2.18 on 2021-03-15 23:10

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0004_auto_20210305_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.Account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='root',
            field=models.IntegerField(blank=True, default=None, help_text='If it is an expense code, the last 5 digits', null=True, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', message='Root must be 5 digits.')]),
        ),
        migrations.AlterField(
            model_name='account',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 15, 23, 10, 23, 185818, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='BillingRecordAccount',
        ),
    ]
