# Generated by Django 2.2.23 on 2021-06-06 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0004_accountuser_billingrecordstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='current_state',
            field=models.CharField(blank=True, help_text='Name of the most recent BillingRecordState', max_length=100, null=True),
        ),
    ]
