# Generated by Django 2.2.28 on 2022-12-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0004_facility_billing_record_calculator'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='facility',
            constraint=models.UniqueConstraint(fields=('name',), name='facility_natural_key'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('product_number',), name='product_natural_key'),
        ),
        migrations.AddConstraint(
            model_name='userproductaccount',
            constraint=models.UniqueConstraint(fields=('account', 'user', 'product'), name='user_product_account_natural_key'),
        ),
    ]
