# Generated by Django 2.2.18 on 2021-03-16 19:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0005_auto_20210315_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 16, 19, 49, 35, 118931, tzinfo=utc)),
        ),
    ]
