# Generated by Django 2.2.24 on 2021-07-01 20:33

from django.db import migrations, models
import ifxbilling.models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0005_billingrecord_current_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='valid_from',
            field=models.DateField(blank=True, default=ifxbilling.models.thisDate),
        ),
    ]
