# Generated by Django 2.2.24 on 2021-07-01 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0005_billingrecord_current_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='funding_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='percent',
            field=models.IntegerField(default=100, help_text='Percent of total product usage cost that this charge represents, defaults to 100%'),
        ),
        migrations.AddField(
            model_name='product',
            name='reporting_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productusage',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productusage',
            name='start_date',
            field=models.DateTimeField(default='2021-07-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='billingrecord',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Description of the billing record.', max_length=200, null=True),
        ),
    ]
