# Generated by Django 3.2.16 on 2023-01-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0005_auto_20221220_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='product_usage_link_text',
            field=models.CharField(blank=True, help_text='Display text for link to associated ProductUsage', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='product_usage_url',
            field=models.CharField(blank=True, help_text='URL link for product usage display.  Should be a full URL so that it works in both facility applications and fiine', max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('product', 'name')},
        ),
    ]
