# Generated by Django 3.2.16 on 2023-03-06 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0006_auto_20230117_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='decimal_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Decimal quantity of the Product used for this billing record', max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='rate_obj',
            field=models.ForeignKey(help_text='The rate used to calculate this charge', null=True, on_delete=django.db.models.deletion.PROTECT, to='ifxbilling.rate'),
        ),
    ]
