# Generated by Django 2.2.24 on 2021-07-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0006_auto_20210701_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingrecord',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Description of the billing record.', max_length=255, null=True),
        ),
    ]
