# Generated by Django 2.2.18 on 2021-02-17 19:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0006_auto_20210217_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 2, 17, 19, 48, 52, 187208, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='rate',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.Product'),
        ),
    ]
