# Generated by Django 3.2.16 on 2023-03-06 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0007_auto_20230306_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
