# Generated by Django 2.2.24 on 2021-07-02 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0006_auto_20210701_2033'),
        ('ifxbilling', '0007_auto_20210701_1624'),
    ]

    operations = [
    ]
