# Generated by Django 3.2.16 on 2023-03-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0008_auto_20230306_1549'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together=set(),
        ),
    ]
