# Generated by Django 2.2.24 on 2021-07-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0008_merge_20210702_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='productusage',
            name='description',
            field=models.CharField(blank=True, help_text='Description of usage', max_length=2000, null=True),
        ),
    ]
