# Generated by Django 3.2.16 on 2023-03-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0009_alter_rate_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='version',
            field=models.IntegerField(default=1, help_text='Version of the rate'),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('product', 'name', 'version')},
        ),
    ]
