# Generated by Django 2.2.24 on 2021-07-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0009_productusage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productusage',
            name='quantity',
            field=models.BigIntegerField(default=1, help_text='Quantity of product'),
        ),
    ]
