# Generated by Django 2.2.24 on 2021-07-20 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ifxbilling', '0010_auto_20210714_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billingrecord_create', to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billingrecord_update', to=settings.AUTH_USER_MODEL, verbose_name='last updated by'),
        ),
    ]
