# Generated by Django 3.2.16 on 2023-03-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0010_auto_20230306_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='End date for the time span billed.', null=True),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Start date for time span billed.', null=True),
        ),
    ]
