# Generated by Django 2.2.24 on 2021-07-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0011_auto_20210720_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='rate',
            field=models.CharField(blank=True, help_text='Text description of the rate used to calculate the charge', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rate',
            field=models.CharField(blank=True, help_text='Text description of the rate used to calculate the charge', max_length=100, null=True),
        ),
    ]
