# Generated by Django 3.2.16 on 2023-03-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0011_auto_20230313_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ('sort_order', '-version')},
        ),
        migrations.AddField(
            model_name='rate',
            name='sort_order',
            field=models.IntegerField(default=1, help_text='Sort order for display purposes'),
        ),
    ]
