# Generated by Django 2.2.24 on 2021-08-17 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0012_auto_20210728_2040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the facility (e.g. Helium Recovery Service)', max_length=200, unique=True)),
                ('application_username', models.CharField(help_text='Username that permits logging in to the facility application (e.g. nice)', max_length=50)),
                ('credit_code', models.CharField(help_text='Credit code to receive funds from billing for product usages.', max_length=50)),
                ('invoice_prefix', models.CharField(help_text='Prefix used in the invoice names for the facility.', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'db_table': 'facility',
            },
        ),
    ]
