# Generated by Django 2.2.24 on 2021-08-17 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0013_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='facility',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.Facility'),
            preserve_default=False,
        ),
    ]
