# Generated by Django 3.2.18 on 2023-07-31 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0013_auto_20230331_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='description',
            field=models.CharField(blank=True, help_text='Description of the rate', max_length=100, null=True),
        ),
    ]
