# Generated by Django 2.2.24 on 2021-08-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0014_product_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='max_qty',
            field=models.IntegerField(blank=True, help_text='Price applys to this number or units or less', null=True),
        ),
    ]
