# Generated by Django 3.2.20 on 2023-08-14 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        # ('ifxuser', '0002_alter_ifxuseraffiliation_id'),
        ('ifxbilling', '0014_rate_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Start time that this rate applies')),
                ('end_date', models.DateField(blank=True, help_text='Time this rate stops applying', null=True)),
                ('organization', models.ForeignKey(help_text='The organization that gets the rate', on_delete=django.db.models.deletion.CASCADE, to='ifxuser.organization')),
                ('rate', models.ForeignKey(help_text='The rate the organization gets', on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.rate')),
            ],
            options={
                'db_table': 'organization_rate',
            },
        ),
    ]
