# Generated by Django 4.2.10 on 2024-02-22 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0015_organizationrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent product for this product', null=True, on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.product'),
        ),
    ]
