# Generated by Django 2.2.24 on 2021-08-24 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0015_rate_max_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='root',
            field=models.CharField(blank=True, default=None, help_text='If it is an expense code, the last 5 digits', max_length=5, null=True, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', message='Root must be 5 digits.')]),
        ),
    ]
