# Generated by Django 2.2.24 on 2021-08-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0015_rate_max_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
