# Generated by Django 4.2.10 on 2024-03-18 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0016_product_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text='Name of the rate tier', max_length=50, unique=True)),
            ],
            options={
                'db_table': 'rate_tier',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='rate_tier',
            field=models.ForeignKey(blank=True, help_text='Rate set for this product', null=True, on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.ratetier'),
        ),
        migrations.AddField(
            model_name='rate',
            name='rate_tier',
            field=models.ForeignKey(blank=True, help_text='The rate tier to which this rate belongs', null=True, on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.ratetier'),
        ),
    ]
