# Generated by Django 4.2.10 on 2024-03-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0016_product_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=models.CharField(default=None, help_text='Product description', max_length=4000),
        ),
    ]
