# Generated by Django 2.2.24 on 2021-09-03 19:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ifxbilling', '0016_auto_20210824_2106'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useraccount',
            unique_together={('account', 'user')},
        ),
    ]
