# Generated by Django 2.2.24 on 2021-09-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0017_auto_20210903_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingrecord',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Description of the billing record.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(default=None, help_text='Reason for this charge.', max_length=500),
        ),
    ]
