# Generated by Django 4.2.10 on 2024-03-18 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0017_ratetier_product_rate_tier_rate_rate_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='product',
            field=models.ForeignKey(blank=True, help_text='The product to which this rate applies', null=True, on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.product'),
        ),
    ]
