# Generated by Django 4.2.13 on 2024-07-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0018_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='object_code_category',
            field=models.CharField(blank=True, choices=[('Laboratory Consumables', 'Laboratory Consumables'), ('Technical Services', 'Technical Services')], default='Technical Services', max_length=100, null=True),
        ),
    ]
