# Generated by Django 2.2.24 on 2021-09-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0018_auto_20210924_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='productusage',
            name='updated',
            field=models.DateTimeField(default='2021-09-28'),
        ),
    ]
