# Generated by Django 2.2.24 on 2021-09-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0019_productusage_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productusage',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
