# Generated by Django 4.2.13 on 2024-07-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0019_product_object_code_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='object_code_category',
            field=models.CharField(blank=True, choices=[('Laboratory Consumables', 'Laboratory Consumables'), ('Technical Services', 'Technical Services'), ('Animal Per Diem Charges', 'Animal Per Diem Charges')], default='Technical Services', max_length=100, null=True),
        ),
    ]
