# Generated by Django 2.2.24 on 2021-10-08 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0020_auto_20210928_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingrecord',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Description of the billing record.', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='productusage',
            name='month',
            field=models.IntegerField(help_text='Month in which the usage occurs'),
        ),
        migrations.AlterField(
            model_name='productusage',
            name='year',
            field=models.IntegerField(help_text='Calendar year in which the usage occurs'),
        ),
    ]
