# Generated by Django 4.2.14 on 2024-08-13 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0020_alter_product_object_code_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='ifxacct',
            field=models.CharField(blank=True, default=None, help_text='IFXACCT', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='ifxfac',
            field=models.CharField(blank=True, default=None, help_text='IFXFAC', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='FacilityCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_code', models.CharField(help_text='Credit code to receive funds from billing for product usages.', max_length=50)),
                ('debit_object_code_category', models.CharField(choices=[('Laboratory Consumables', 'Laboratory Consumables'), ('Technical Services', 'Technical Services'), ('Animal Per Diem Charges', 'Animal Per Diem Charges')], default='Technical Services', max_length=100)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.facility')),
            ],
            options={
                'verbose_name_plural': 'facility codes',
                'db_table': 'facility_codes',
            },
        ),
    ]
