# Generated by Django 2.2.24 on 2021-10-12 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0021_auto_20211008_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductUsageProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.CharField(blank=True, help_text='Error message from processing into billing record.', max_length=20000, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('billing_record', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ifxbilling.BillingRecord')),
                ('product_usage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ifxbilling.ProductUsage')),
            ],
            options={
                'db_table': 'product_usage_processing',
            },
        ),
    ]
