# Generated by Django 4.2.15 on 2024-08-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0021_account_ifxacct_facility_ifxfac_facilitycodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=models.CharField(help_text='EC or PO + institution', max_length=100),
        ),
    ]
