# Generated by Django 2.2.24 on 2021-10-12 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0022_productusageprocessing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productusageprocessing',
            name='billing_record',
        ),
    ]
