# Generated by Django 4.2.15 on 2024-08-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0022_alter_account_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=models.CharField(help_text='EC or PO + institution', max_length=100, unique=True),
        ),
    ]
