# Generated by Django 2.2.24 on 2021-10-26 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0023_remove_productusageprocessing_billing_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productusageprocessing',
            name='error_message',
            field=models.CharField(blank=True, help_text='Error message from processing into billing record.', max_length=2000, null=True),
        ),
    ]
