# Generated by Django 4.2.15 on 2024-09-18 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifxuser', '0005_ifxuser_citizenship_ifxuser_ethnicity_ifxuser_gender_and_more'),
        ('ifxbilling', '0023_alter_account_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitycodes',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organization responsible for the account.', null=True, on_delete=django.db.models.deletion.PROTECT, to='ifxuser.organization'),
        ),
    ]
