# Generated by Django 2.2.24 on 2021-11-02 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifxuser', '0011_auto_20210727_1929'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ifxbilling', '0024_auto_20211026_1759'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='productusage',
        #     name='logged_by',
        #     field=models.ForeignKey(default=1, help_text='User that logged the usage (may be different than user)', on_delete=django.db.models.deletion.PROTECT, related_name='product_usage_logger', to=settings.AUTH_USER_MODEL),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='productusage',
        #     name='organization',
        #     field=models.ForeignKey(default=1, help_text='Organization responsible for the account.', on_delete=django.db.models.deletion.PROTECT, to='ifxuser.Organization'),
        #     preserve_default=False,
        # ),
    ]
