# Generated by Django 4.2.19 on 2025-04-01 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifxuser', '0009_alter_ifxuser_groups_alter_ifxuser_user_permissions'),
        ('ifxbilling', '0024_facilitycodes_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_organization',
            field=models.ForeignKey(blank=True, help_text='Organization responsible for the account.', null=True, on_delete=django.db.models.deletion.PROTECT, to='ifxuser.organization'),
        ),
    ]
