# Generated by Django 4.2.20 on 2025-05-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0025_product_product_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default=None, help_text='Name of the product', max_length=100, unique=True),
        ),
    ]
