# Generated by Django 2.2.24 on 2021-11-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0025_auto_20211102_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='object_code',
            field=models.CharField(default='8250', help_text='Object code for this facility', max_length=4),
        ),
    ]
