# Generated by Django 2.2.25 on 2021-12-16 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0026_facility_object_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingrecord',
            name='product_usage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ifxbilling.ProductUsage'),
        ),
    ]
