# Generated by Django 4.2.23 on 2025-12-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0026_alter_product_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is this product currently active?'),
        ),
    ]
