# Generated by Django 2.2.26 on 2022-01-21 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0027_auto_20211216_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='billable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productusage',
            name='billable',
            field=models.BooleanField(default=False),
        ),
    ]
