# Generated by Django 2.2.26 on 2022-01-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifxbilling', '0028_auto_20220121_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productusage',
            name='billable',
        ),
        migrations.AlterField(
            model_name='product',
            name='billable',
            field=models.BooleanField(default=True),
        ),
    ]
