"""
Django settings for ifxbilling project.

Generated by 'django-admin startproject' using Django 2.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os
from decimal import Decimal

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('IFXBILLING_DJANGO_KEY','lkoqwimoismoaiwelj23ajsd')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('IFXBILLING_DEBUG', 'FALSE').upper() == 'TRUE'
LOGLEVEL = os.environ.get('IFXBILLING_LOGLEVEL', 'INFO')

IFXBILLING_PROCESSOR_MODULE = 'test'
AUTH_USER_MODEL = 'ifxuser.IfxUser'
DB_USERNAME = os.environ.get('IFXBILLING_USERNAME', 'ifxbilling')
DB_PASSWORD = os.environ.get('IFXBILLING_PASSWORD', 'ifxbilling')
DB_DATABASE = os.environ.get('IFXBILLING_DATABASE', 'ifxbilling')
DB_HOSTNAME = os.environ.get('IFXBILLING_HOSTNAME', 'ifxbilling')

ALLOWED_HOSTS = ['*']

IFX_APP = {
    'token': os.environ.get('IFXBILLING_IFX_APP_TOKEN'),
    'name': 'ifxbilling',
}

if IFX_APP['token'] == 'FIXME':
    print('HEY!!!!!  Set the IFX_APP_TOKEN in docker-compose!')

IFX_AUTH_META_KEY = 'HTTP_HKEY_EDUPERSONPRINCIPALNAME'

# Application definition

INSTALLED_APPS = [
    'ifxuser',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'author',
    'djvocab',
    'ifxauth',
    'drf_yasg',
    'ifxbilling',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'ifxauth.auth.IfxRemoteUserMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'author.middlewares.AuthorDefaultBackendMiddleware',
]

#AUTHENTICATION_BACKENDS = [
#    'ifxauth.auth.IfxRemoteUserBackend',
#]

ROOT_URLCONF = 'ifxbilling.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wsgi.application'

DATABASES = {
    'default': {
        'ENGINE':       'django.db.backends.mysql',
        'NAME':         DB_DATABASE,
        'USER':         DB_USERNAME,
        'PASSWORD':     DB_PASSWORD,
        'HOST':         DB_HOSTNAME,
        'PORT':         3306,
        'OPTIONS': {
            'charset': 'utf8mb4',
            'use_unicode': True,
            'init_command': 'SET storage_engine=INNODB,character_set_connection=utf8mb4,collation_connection=utf8mb4_unicode_ci,group_concat_max_len=50000'
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

## Logging setup
# Logging setup.  Meant to log everything to stderrr
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse'
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue'
        },
    },
    'formatters': {
        'console': {
            'format': '%(asctime)s %(name)-12s %(levelname)-8s %(message)s',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'console',
            'level': LOGLEVEL,
            'filters': ['require_debug_false'],
        },
        'console_debug': {
            'class': 'logging.StreamHandler',
            'formatter': 'console',
            'level': LOGLEVEL,
            'filters': ['require_debug_true'],
        },
        'mail_admins_debug': {
            'class': 'django.utils.log.AdminEmailHandler',
            'level': 'ERROR',
            'filters': ['require_debug_true'],
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
        },
    },
    'loggers': {
        'ifxbilling': {
            'handlers': ['console', 'console_debug', 'mail_admins'],
            'level': LOGLEVEL,
            'propagate': False,
        }
    },
}

class GROUPS():
    '''
    Group names
    '''
    ADMIN_GROUP_NAME = 'Admin'
    PREFERRED_BILLING_RECORD_APPROVAL_ACCOUNT_GROUP_NAME = 'Preferred Billing Record Approval Account Group Name'


AUTHOR_IGNORE_MODELS = [
    'ifxbilling.BillingRecord',
    'ifxbilling.Transaction',
]

DEFAULT_EMAIL_FROM_ADDRESS = 'ifx@fas.harvard.edu'

class EMAILS():
    '''
    Email addresses
    '''
    DEFAULT_EMAIL_FROM_ADDRESS = DEFAULT_EMAIL_FROM_ADDRESS

class IFXMESSAGES():
    '''
    ifxmail message names
    '''
    EXPENSE_CODE_REQUEST_MESSAGE_NAME = 'ifxbilling_expense_code_request_message'


SWAGGER_SETTINGS = {
   'DEFAULT_INFO': 'ifxbilling.urls.API_INFO',
}

STANDARD_QUANTIZE = Decimal('0.0000')
TWO_DIGIT_QUANTIZE = Decimal('0.00')
